window.addEventListener("error",event=>{window.prismStartupError=event.message||"Gallery startup error"});

const seed=[
 {id:1,name:"Mountains",cat:"Camera",date:"16 Sep 2026",tags:["Mountain","Nature"],src:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85"},
 {id:2,name:"Forest Light",cat:"Camera",date:"14 Sep 2026",tags:["Forest","Nature"],src:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=85"},
 {id:3,name:"City Night",cat:"Downloads",date:"12 Sep 2026",tags:["City","Night"],src:"https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=900&q=85"},
 {id:4,name:"Ocean",cat:"Favourites",date:"10 Sep 2026",tags:["Ocean","Travel"],src:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85"},
 {id:5,name:"Architecture",cat:"Camera",date:"08 Sep 2026",tags:["Building","City"],src:"https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=900&q=85"},
 {id:6,name:"Golden Hour",cat:"Favourites",date:"03 Sep 2026",tags:["Sunset","Golden"],src:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85"},
 {id:7,name:"Lake",cat:"Camera",date:"29 Aug 2026",tags:["Lake","Nature"],src:"https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=85"},
 {id:8,name:"Portrait",cat:"Camera",date:"25 Aug 2026",tags:["Portrait","People"],src:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85"}
];
let photos=seed;try{let savedPhotos=localStorage.getItem("prismPhotos");if(savedPhotos){let parsedPhotos=JSON.parse(savedPhotos);if(Array.isArray(parsedPhotos))photos=parsedPhotos}}catch(error){console.warn("Saved gallery data could not be read; loading sample photos.",error)}
photos=photos.filter(p=>p&&typeof p==="object").map((p,i)=>({...p,id:p.id??("photo-"+i),name:p.name||"Photo",cat:p.cat||"",date:p.date||"",tags:Array.isArray(p.tags)?p.tags:[],src:typeof p.src==="string"?p.src:""})).filter(p=>p.src);
for(let p of seed)if(!photos.some(x=>x.id===p.id))photos.unshift({...p});
let category="All",current=null,zoom=1,wallIndex=0,wallPaused=false,wallTimer=null,lockedAccess=false,edit={brightness:100,contrast:100,saturation:100,highlights:0,shadows:0,warmth:0,vibrance:0,blur:0,sharpen:0};
const $=id=>document.getElementById(id);
function save(){try{localStorage.setItem("prismPhotos",JSON.stringify(photos))}catch(error){console.warn("Browser storage is full; changes could not be saved.",error)}}
// Connect importing immediately so it remains usable even if another gallery feature fails to initialize.
$("uploadBtn").onclick=()=>$("fileInput").click();
$("fileInput").onchange=e=>{[...e.target.files].forEach((f,i)=>{let r=new FileReader();r.onload=()=>{photos.unshift({id:Date.now()+i,name:f.name.replace(/\.[^.]+$/,""),cat:/screen|screenshot/i.test(f.name)?"Screenshots":"Camera",date:new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}),tags:guessTags(f.name),src:r.result});save();render()};r.readAsDataURL(f)});e.target.value=""};
function sampleScreenshot(name,accent,headline,lines,id){let rows=lines.map((line,i)=>`<rect x="28" y="${205+i*75}" width="324" height="58" rx="12" fill="#fff"/><circle cx="56" cy="${234+i*75}" r="15" fill="${accent}" opacity=".18"/><text x="82" y="${230+i*75}" font-size="12" fill="#25263a">${line}</text><text x="82" y="${249+i*75}" font-size="9" fill="#8a8b9a">Saved for later</text>`).join("");let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="380" height="720" viewBox="0 0 380 720"><rect width="380" height="720" rx="30" fill="#f3f4f8"/><rect x="0" y="0" width="380" height="160" rx="30" fill="${accent}"/><rect x="0" y="130" width="380" height="40" fill="${accent}"/><text x="28" y="42" font-size="11" fill="#fff" opacity=".8">9:41  ◉  ▰</text><text x="28" y="100" font-size="23" font-weight="700" fill="#fff">${headline}</text><text x="28" y="135" font-size="11" fill="#fff" opacity=".85">Your saved collection</text><text x="28" y="194" font-size="11" fill="#666879">RECENTLY SAVED</text>${rows}<rect x="28" y="468" width="324" height="110" rx="14" fill="${accent}" opacity=".12"/><text x="48" y="510" font-size="13" font-weight="700" fill="#303146">A little inspiration</text><text x="48" y="534" font-size="10" fill="#666879">Ideas and places worth remembering</text><rect x="28" y="615" width="324" height="56" rx="18" fill="#fff"/><text x="72" y="648" font-size="10" fill="#666879">Home     Search     Collections     Profile</text></svg>`;return{id,name,cat:"Screenshots",date:"07 Oct 2026",tags:["Screenshot","Sample"],src:"data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svg)}}
let screenshotSamples=[sampleScreenshot("Travel Ideas","#705cf5","Places to go",["Kyoto in spring","Coastal weekend","Mountain cabin"],"sample-screen-1"),sampleScreenshot("Reading List","#e78164","On my reading list",["The Creative Act","A Field Guide to Getting Lost","Small Things Like These"],"sample-screen-2"),sampleScreenshot("Recipe Notes","#42a88d","Recipes to try",["Lemon pasta","Sunday pancakes","Roasted tomato soup"],"sample-screen-3")];let addedSamples=false;for(let p of screenshotSamples)if(!photos.some(x=>x.id===p.id)){photos.push(p);addedSamples=true}if(addedSamples)save();
function filtered(){let q=$("search").value.toLowerCase().trim();return photos.filter(p=>(p.cat!=="Locked"||lockedAccess)&&(category==="All"||category==="Favourites"?(category==="All"||p.cat==="Favourites"||p.favorite):(p.cat===category))&&(!q||(p.name+" "+p.cat+" "+p.tags.join(" ")+" "+p.date).toLowerCase().includes(q))) }
function render(){let g=$("gallery"),arr=filtered(),lockedCount=photos.filter(p=>p.cat==="Locked").length;g.innerHTML=arr.length?arr.map(p=>`<article class="card" data-id="${p.id}"><button class="fav" data-fav="${p.id}">${p.favorite?"♥":"♡"}</button><img loading="lazy" src="${p.src}" alt="${p.name}" onerror="this.style.display='none';this.parentElement.classList.add('image-missing')"><div class="overlay"><div class="meta">${p.name}</div><div class="sub">${p.cat} · ${p.tags.join(", ")}</div></div></article>`).join(""):category==="All"&&lockedCount? `<div class="empty">Your ${lockedCount} photo${lockedCount===1?" is":"s are"} in Locked. <button class="btn" data-open-locked>Enter password to view</button></div>`:`<div class="empty">No photos match this view.</div>`;renderWall()}
function renderWall(){let items=photos.filter(p=>p.cat!=="Trash"&&(p.cat!=="Locked"||lockedAccess));if(!items.length){$("wallName").textContent="Add photos to start your wall";$("wallDate").textContent="";$("wallStatus").textContent="No photos to play";$("wallImg").removeAttribute("src");$("wallDots").innerHTML="";return}wallIndex=((wallIndex%items.length)+items.length)%items.length;let p=items[wallIndex];$("wallImg").src=p.src;$("wallImg").alt=p.name;$("wallName").textContent=p.name;$("wallDate").textContent=p.date;$("wallStatus").textContent=`Memory ${wallIndex+1} of ${items.length} · ${wallPaused?"Paused":"Playing"}`;$("wallDots").innerHTML=items.map((_,i)=>`<button class="wall-dot ${i===wallIndex?"active":""}" data-wall-index="${i}" aria-label="Show memory ${i+1}"></button>`).join("")}
function moveWall(step){let count=photos.filter(p=>p.cat!=="Trash"&&(p.cat!=="Locked"||lockedAccess)).length;if(!count)return;wallIndex=(wallIndex+step+count)%count;renderWall()}
$("wallPrev").onclick=()=>moveWall(-1);$("wallNext").onclick=()=>moveWall(1);
$("wallPlay").onclick=()=>{wallPaused=!wallPaused;$("wallPlay").textContent=wallPaused?"Play":"Pause";$("wallPlay").setAttribute("aria-label",wallPaused?"Play slideshow":"Pause slideshow");renderWall()};
$("wallDots").onclick=e=>{let dot=e.target.closest("[data-wall-index]");if(dot){wallIndex=+dot.dataset.wallIndex;renderWall()}};
$("wallSlide").onclick=()=>{let p=photos.filter(x=>x.cat!=="Trash"&&(x.cat!=="Locked"||lockedAccess))[wallIndex];if(p)openViewer(p.id)};
wallTimer=setInterval(()=>{if(!wallPaused)moveWall(1)},5000);
async function scanDuplicates(){let box=$("duplicates"),button=$("scanDuplicates");button.disabled=true;button.textContent="Scanning…";box.innerHTML='<div class="empty">Checking for identical image files…</div>';let groups=new Map();for(let p of photos.filter(x=>x.cat!=="Trash"&&(x.cat!=="Locked"||lockedAccess))){let key=p.src;if(p.src.startsWith("data:")||p.src.startsWith("blob:"))try{let bytes=await fetch(p.src).then(r=>r.arrayBuffer()),digest=await crypto.subtle.digest("SHA-256",bytes);key=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}catch(_){}if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p)}let dupes=[...groups.values()].filter(g=>g.length>1);box.innerHTML=dupes.length?dupes.map((g,i)=>`<article class="duplicate-group"><div class="duplicate-label"><strong>${g.length} identical copies</strong><span>Keep one copy; remove the extras.</span></div><div class="duplicate-thumbs">${g.map((p,j)=>`<div class="duplicate-thumb"><img src="${p.src}" alt="${p.name}"><span>${p.name}${j===0?" · Keep":""}</span></div>`).join("")}</div><button class="btn danger duplicate-delete" data-duplicate-group="${i}">Delete ${g.length-1} extra ${g.length===2?"copy":"copies"}</button></article>`).join(""):'<div class="empty">No duplicate images found.</div>';box.dataset.groups=JSON.stringify(dupes.map(g=>g.slice(1).map(p=>p.id)));button.disabled=false;button.textContent="Scan again"}
function signatureDistance(a,b){let n=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])n++;return n}
async function imageSignature(photo){try{let img=await loadImage(photo.src),c=document.createElement("canvas"),ctx=c.getContext("2d",{willReadFrequently:true});c.width=9;c.height=8;ctx.drawImage(img,0,0,9,8);let px=ctx.getImageData(0,0,9,8).data,bits="";for(let y=0;y<8;y++)for(let x=0;x<8;x++){let a=(y*9+x)*4,b=a+4,la=.299*px[a]+.587*px[a+1]+.114*px[a+2],lb=.299*px[b]+.587*px[b+1]+.114*px[b+2];bits+=la>lb?"1":"0"}return bits}catch(_){return"source:"+photo.src}}
async function scanVisualDuplicates(){let box=$("duplicates"),button=$("scanDuplicates"),summary=$("duplicateSummary"),items=photos.filter(p=>p.cat!=="Trash"&&(p.cat!=="Locked"||lockedAccess));button.disabled=true;button.textContent="Scanning...";summary.textContent=`Scanning ${items.length} photos...`;box.innerHTML='<div class="empty">Comparing image contents...</div>';try{let groups=[];for(let [i,photo] of items.entries()){let signature=await imageSignature(photo),group=groups.find(g=>signatureDistance(g.signature,signature)<=2);if(group)group.photos.push(photo);else groups.push({signature,photos:[photo]});summary.textContent=`Scanned ${i+1} of ${items.length} photos...`}let duplicates=groups.filter(g=>g.photos.length>1);box.innerHTML=duplicates.length?duplicates.map((g,i)=>`<article class="duplicate-group"><div class="duplicate-label"><strong>${g.photos.length} matching images</strong><span>Keep one; delete the extra copies.</span></div><div class="duplicate-thumbs">${g.photos.map((p,j)=>`<div class="duplicate-thumb"><img src="${p.src}" alt="${p.name}"><span>${p.name}${j===0?" · Keep":""}</span></div>`).join("")}</div><button class="btn danger duplicate-delete" data-duplicate-group="${i}">Delete ${g.photos.length-1} extra ${g.photos.length===2?"copy":"copies"}</button></article>`).join(""):'<div class="empty">No duplicate images found. Try adding the same picture in another format and scan again.</div>';box.dataset.groups=JSON.stringify(duplicates.map(g=>g.photos.slice(1).map(p=>p.id)));summary.textContent=duplicates.length?`Found ${duplicates.length} duplicate group${duplicates.length===1?"":"s"} among ${items.length} photos.`:`Scanned ${items.length} photos. No duplicates found.`}catch(error){summary.textContent="Scan failed. Please try again.";box.innerHTML='<div class="empty">The scan could not read one or more photos. Try again.</div>';console.error("Duplicate scan failed",error)}finally{button.disabled=false;button.textContent="Scan again"}}
$("scanDuplicates").onclick=scanVisualDuplicates;
$("scanDuplicatesTop").onclick=()=>{$("duplicateSection").scrollIntoView({behavior:"smooth"});scanVisualDuplicates()};
$("duplicates").onclick=e=>{let b=e.target.closest("[data-duplicate-group]");if(!b)return;let groups=JSON.parse($("duplicates").dataset.groups||"[]"),ids=groups[+b.dataset.duplicateGroup]||[];photos=photos.filter(p=>!ids.includes(p.id));save();render();scanVisualDuplicates()};
$("chips").onclick=e=>{let b=e.target.closest("[data-cat]");if(!b)return;showCategory(b.dataset.cat,b)}
function showCategory(next,button){if(next==="Locked"&&!lockedAccess){if(prompt("Enter the password to open Locked photos")!=="1101"){alert("Incorrect password.");return}lockedAccess=true}if(next!=="Locked")lockedAccess=false;category=next;document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));(button||document.querySelector(`[data-cat="${next}"]`))?.classList.add("active");render()}
$("gallery").addEventListener("click",e=>{if(e.target.closest("[data-open-locked]"))showCategory("Locked")});
$("search").oninput=render;
$("gallery").onclick=e=>{let fav=e.target.closest("[data-fav]");if(fav){let p=photos.find(x=>x.id==fav.dataset.fav);p.favorite=!p.favorite;p.cat=p.favorite&&p.cat==="Trash"?"Favourites":p.cat;save();render();return}let c=e.target.closest(".card");if(c)openViewer(+c.dataset.id)}
function openViewer(id){current=photos.find(p=>p.id===id);zoom=1;updateViewer();$("lockBtn").textContent=current.cat==="Locked"?"Unlock photo":"Lock photo";$("modal").classList.add("show")}
function updateViewer(){if(!current)return;$("viewImg").src=current.src;$("viewImg").style.transform=`scale(${zoom})`;$("viewName").textContent=current.name;$("viewDate").textContent=current.date;$("favBtn").textContent=current.favorite?"Favorited":"Favorite";$("viewInfo").innerHTML=`<div><small>Category</small>${current.cat}</div><div><small>AI Tags</small>${current.tags.join(", ")}</div><div><small>Favorite</small>${current.favorite?"Yes":"No"}</div><div><small>Timeline</small>${current.date}</div>`}
$("closeViewer").onclick=()=>{$("modal").classList.remove("show")};
$("modal").onclick=e=>{if(e.target===$("modal"))$("modal").classList.remove("show")};
$("favBtn").onclick=()=>{current.favorite=!current.favorite;save();updateViewer();render()};
$("lockBtn").onclick=()=>{if(current.cat==="Locked"){current.cat=current.previousCategory||"Camera";delete current.previousCategory}else{current.previousCategory=current.cat;current.cat="Locked"}save();$("lockBtn").textContent=current.cat==="Locked"?"Unlock photo":"Lock photo";updateViewer();render()};
$("trashBtn").onclick=()=>{current.cat="Trash";current.favorite=false;save();$("modal").classList.remove("show");render()};
$("downloadBtn").onclick=()=>{let a=document.createElement("a");a.href=current.src;a.download=current.name+".jpg";a.target="_blank";a.click()};
document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));
function applyPreset(p){let f={Original:"none",Vintage:"sepia(.45) saturate(.8) contrast(1.05)",Cinema:"contrast(1.22) saturate(1.08)",Golden:"sepia(.22) saturate(1.25) brightness(1.06)",Rose:"sepia(.15) hue-rotate(320deg) saturate(1.15)",Cool:"hue-rotate(18deg) saturate(.95) brightness(1.02)",Vivid:"saturate(1.6) contrast(1.08)","B&W":"grayscale(1)"}[p];$("viewImg").style.filter=f}
$("viewImg").onwheel=e=>{e.preventDefault();zoom=Math.max(.5,Math.min(3,zoom+(e.deltaY<0?.1:-.1)));$("viewImg").style.transform=`scale(${zoom})`};
document.onkeydown=e=>{if(!$("modal").classList.contains("show"))return;if(e.key==="Escape")$("modal").classList.remove("show");if(e.key==="ArrowRight"){let a=filtered(),i=a.findIndex(x=>x.id===current.id);openViewer(a[(i+1)%a.length].id)}if(e.key==="ArrowLeft"){let a=filtered(),i=a.findIndex(x=>x.id===current.id);openViewer(a[(i-1+a.length)%a.length].id)}};
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("editor").classList.contains("show"))$("editor").classList.remove("show")});
const defaultEdit=()=>({brightness:100,contrast:100,saturation:100,highlights:0,shadows:0,warmth:0,vibrance:0,blur:0,sharpen:0});
$("editBtn").onclick=()=>{edit=defaultEdit();$("editImg").src=current.src;syncEdit();$("editor").classList.add("show")};
$("editorClose").onclick=()=>$("editor").classList.remove("show");
const editKeys=["brightness","contrast","saturation","highlights","shadows","warmth","vibrance","blur","sharpen"];
editKeys.forEach(k=>$(k).oninput=()=>{edit[k]=+$(k).value;syncEdit()});
function syncEdit(){for(let k of editKeys)$(k).value=edit[k];for(let k of editKeys){let out=$(k+"Val");if(out)out.textContent=({brightness:edit.brightness+"%",contrast:edit.contrast+"%",saturation:edit.saturation+"%",highlights:edit.highlights,shadows:edit.shadows,warmth:edit.warmth,vibrance:edit.vibrance,blur:edit.blur+"px",sharpen:edit.sharpen})[k]}let vibrance=1+edit.vibrance/100;$("editImg").style.filter=`brightness(${edit.brightness/100}) contrast(${edit.contrast/100}) saturate(${edit.saturation/100*vibrance}) sepia(${Math.max(0,edit.warmth)/130}) hue-rotate(${Math.min(0,edit.warmth)*.35}deg) blur(${edit.blur}px)`}
$("resetEdit").onclick=()=>{edit=defaultEdit();syncEdit()};
// Estimate exposure and color from a small sample, then choose restrained corrective values.
$("autoBtn").onclick=async()=>{let button=$("autoBtn");button.disabled=true;button.textContent="Analyzing photo…";let next=defaultEdit();try{let img=await loadImage(current.src),c=document.createElement("canvas"),ctx=c.getContext("2d",{willReadFrequently:true});c.width=48;c.height=48;ctx.drawImage(img,0,0,48,48);let d=ctx.getImageData(0,0,48,48).data,lum=0,sat=0,n=0;for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2];lum+=(.2126*r+.7152*g+.0722*b)/255;sat+=(Math.max(r,g,b)-Math.min(r,g,b))/Math.max(1,Math.max(r,g,b));n++}lum/=n;sat/=n;next.brightness=Math.round(clamp(100+(.48-lum)*30,94,116));next.contrast=Math.round(clamp(100+(.46-lum)*22,96,112));next.saturation=Math.round(clamp(104+(.42-sat)*16,100,112));next.shadows=Math.round(clamp((.42-lum)*28,-4,12));next.highlights=Math.round(clamp((lum-.58)*-25,-10,3));next.sharpen=1}catch(err){next={...next,brightness:106,contrast:106,saturation:106,shadows:5,sharpen:1};console.info("Auto analysis unavailable; using a gentle enhancement.",err)}edit=next;syncEdit();button.disabled=false;button.textContent="🤖 AI Auto Enhance"};
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function loadImage(src){return new Promise((resolve,reject)=>{let img=new Image();if(!src.startsWith("data:"))img.crossOrigin="anonymous";img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
$("saveEdit").onclick=async()=>{let button=$("saveEdit");button.disabled=true;try{let img=await loadImage(current.src),c=document.createElement("canvas"),ctx=c.getContext("2d",{willReadFrequently:true});c.width=img.naturalWidth;c.height=img.naturalHeight;ctx.filter=`brightness(${edit.brightness/100}) contrast(${edit.contrast/100}) saturate(${edit.saturation/100*(1+edit.vibrance/100)}) sepia(${Math.max(0,edit.warmth)/130}) hue-rotate(${Math.min(0,edit.warmth)*.35}deg) blur(${edit.blur}px)`;ctx.drawImage(img,0,0);ctx.filter="none";let pixels=ctx.getImageData(0,0,c.width,c.height),d=pixels.data;for(let i=0;i<d.length;i+=4){for(let ch=0;ch<3;ch++){let x=d[i+ch]/255,shadow=edit.shadows/100*Math.pow(1-x,2),highlight=edit.highlights/100*Math.pow(x,2);d[i+ch]=clamp(Math.round((x+shadow+highlight)*255+(ch===0?edit.warmth:ch===2?-edit.warmth:0)*.55),0,255)}}ctx.putImageData(pixels,0,0);if(edit.sharpen>0){let original=ctx.getImageData(0,0,c.width,c.height),src=original.data,out=ctx.createImageData(c.width,c.height);out.data.set(src);let strength=edit.sharpen*.22;for(let y=1;y<c.height-1;y++)for(let x=1;x<c.width-1;x++){let i=(y*c.width+x)*4;for(let ch=0;ch<3;ch++){let blur=(src[i-4+ch]+src[i+4+ch]+src[i-c.width*4+ch]+src[i+c.width*4+ch])/4;out.data[i+ch]=clamp(src[i+ch]+(src[i+ch]-blur)*strength,0,255)}}ctx.putImageData(out,0,0)}let data=c.toDataURL("image/jpeg",.92),a=document.createElement("a");a.href=data;a.download=current.name+"-edited.jpg";a.click();current.src=data;save();updateViewer();render();$("editImg").src=data;$("editor").classList.remove("show")}catch(err){alert("This image could not be exported. Try an uploaded photo or a different image source.");console.error(err)}finally{button.disabled=false}};
function guessTags(n){let s=n.toLowerCase(),t=[];for(let [k,v] of [["mountain","Mountain"],["forest","Forest"],["beach","Ocean"],["sea","Ocean"],["screen","Screenshot"],["screenshot","Screenshot"],["city","City"],["sun","Sunset"],["portrait","Portrait"]])if(s.includes(k))t.push(v);return t.length?t:["Photo","Imported"]}
render();window.prismGalleryReady=true;scanVisualDuplicates();


if(!window.prismGalleryReady){
  const gallery=document.getElementById("gallery"),input=document.getElementById("fileInput"),upload=document.getElementById("uploadBtn");
  const fallbackSeeds=[
    {id:"fallback-1",name:"Mountains",cat:"Camera",tags:["Mountain","Nature"],src:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85"},
    {id:"fallback-2",name:"Forest Light",cat:"Camera",tags:["Forest","Nature"],src:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=85"},
    {id:"fallback-3",name:"Ocean",cat:"Camera",tags:["Ocean","Travel"],src:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85"}
  ];
  let fallbackPhotos=[];try{const stored=JSON.parse(localStorage.getItem("prismPhotos")||"[]");if(Array.isArray(stored))fallbackPhotos=stored.filter(p=>p&&p.src)}catch(_){}
  for(const sample of fallbackSeeds)if(!fallbackPhotos.some(p=>p.id===sample.id||p.name===sample.name))fallbackPhotos.unshift(sample);
  function showFallback(){gallery.innerHTML=fallbackPhotos.map(p=>{const card=document.createElement("article");card.className="card";const img=document.createElement("img");img.src=p.src;img.alt=p.name||"Photo";img.onerror=()=>img.style.display="none";const name=document.createElement("div");name.className="overlay";name.textContent=p.name||"Photo";card.append(img,name);return card}).reduce((html,card)=>html+card.outerHTML,"");}
  showFallback();
  if(fallbackPhotos[0]){const wall=document.getElementById("wallImg");wall.src=fallbackPhotos[0].src;document.getElementById("wallName").textContent=fallbackPhotos[0].name||"Memory"}
  upload.onclick=()=>input.click();
  input.onchange=event=>{[...event.target.files].forEach(file=>{const reader=new FileReader();reader.onload=()=>{fallbackPhotos.unshift({id:Date.now()+Math.random(),name:file.name.replace(/\.[^.]+$/,""),cat:"Camera",tags:["Imported"],src:reader.result});showFallback();try{localStorage.setItem("prismPhotos",JSON.stringify(fallbackPhotos))}catch(_){}};reader.readAsDataURL(file)});input.value=""};
  if(window.prismStartupError)console.error("Gallery recovery mode:",window.prismStartupError);
}
